---
title: "Erkenntnisse: Das nehmen wir mit"
#order: 3
---

Unsere Arbeit in GeoStat hat gezeigt: Innovation in der Lehre ist nicht immer einfach – sondern ein Prozess, der Geduld, Ressourcen und den Mut zur Veränderung braucht. Aber sie lohnt sich!

## Ko-kreative Lehrentwicklung braucht strukturelle Unterstützung

Eine zentrale Erkenntnis ist, dass Lehrentwicklung parallel zur laufenden Lehre extrem anspruchsvoll ist. Der Spagat zwischen Projektarbeit, Erprobung neuer Methoden und dem regulären Lehrbetrieb erfordert klare Priorisierung, viel Flexibilität – und vor allem Zeit, die im akademischen Alltag oft fehlt. Ohne die finanzielle Förderung und den Freiraum als StIL-Projekt wäre unsere Arbeit so nicht möglich gewesen.

## Students-as-Partners ist voraussetzungsreich

Ein weiterer entscheidender Faktor für den Erfolg war der Students-as-Partners-Ansatz. Besonders wertvoll ist die Zusammenarbeit mit Studierenden, die fachlich gut verankert sind, finanziell entlohnt und intrinsisch motiviert mitarbeiten. Nur dann können sie als gleichberechtigte Partner:innen agieren und wertvolle Perspektiven einbringen – etwa, indem sie Lernhürden aus ihrer Sicht beschreiben oder Materialien mitgestalten.

## Multi-Perspektivität führt zu robusteren Lehrkonzepten

Gleichzeitig hat uns die Erfahrung gelehrt, dass die bewusste Integration verschiedener Perspektiven – von Fachwissenschaft über Didaktik bis hin zu den Studierenden selbst – klassische Hierarchien aufbricht. Das führt zu robusteren, praxisnahen Lehrkonzepten, die nicht nur die nicht nur theoretisch fundiert, sondern auch im Lehralltag erprobt und bewährt sind.

## Auch die Forschung profitiert

Besonders erfreulich für uns ist, dass auch Lernende auf Doc- und Post-Doc-Niveau von unseren Ansätzen profitieren. Ihnen hilft die systematische Erschließung statistischer Konzepte – etwa durch visuelle Zugänge oder die Verknüpfung von Theorie und Praxis – statistische Wissensgebiete, die für ihre Forschung relevant sind, schneller und nachhaltiger zu erschließen.

## Ein Modell für eine neue Lehr-Lern-Kultur?

Gleichzeitig hat die Auseinandersetzung mit den Studierenden unser eigenes Verständnis vertieft: Als Fachlehrender und Hochschuldidaktikerin haben wir aus der Arbeit miteinander und mit den Studierenden extrem viel gelernt – fachlich wie didaktisch. Das funktionierte nur, weil wir selbst konsequent zu Lernenden und Forschenden im ‚Gelände‘ geworden sind: Wir haben vorgefertigte Vorstellungen zurückgestellt, uns der Reibung miteinander ausgesetzt und den Mut gehabt, uns auf diesen Prozess einzulassen. So wurde GeoStat nicht nur zu einem Projekt für bessere Statistik-Lehre, sondern zu einem Modell für eine neue Lehr-Lern-Kultur – eines, das Lernen als gemeinsamen, dynamischen Prozess versteht.
